name: pibohealth
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.8.3
  qr_flutter: ^4.0.0
  image_picker: ^1.0.4
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/pibo.png